### ISSUE TITLE
IpRangeIter breaks memory safety

### ISSUE THREAD

**Issue by Ofenhed** [sticnarf/iprange-rs#11]
Since IpRangeIter doesn't hold a lifetime, it's possible within safe Rust to cause memory errors. For example:

```rust
pub fn iter(&self) -> IpRangeIter<N>
```

The lifetime from `&self` is dropped here. The issue is the same in most functions related to `IpRangeIter`, including IntoIterator:

```rust
impl<'a, N> IntoIterator for &'a IpRange<N>
where
    N: IpNet + ToNetwork<N> + Clone,
{
    type Item = N;
    type IntoIter = IpRangeIter<N>;

    fn into_iter(self) -> Self::IntoIter {
        let mut queue = VecDeque::new();
        if let Some(root) = self.trie.root.as_ref() {
            let state: N::S = root.init_traverse_state();
            queue.push_back(state);
        }
        IpRangeIter { queue }
    }
}
```

Here, `data Item` and `data IntoIter` also has the lifetime 'a, but this is hidden from the compiler.

It seems that this error originates in that `Ipv4TraverseState` and `Ipv6TraverseState` holds `*const` pointers instead of references Rust is able to keep track of. This unsafe code seems to be why this bug is not detected by the compiler.

```rust
fn node(&self) -> &IpTrieNode {
    unsafe { &*self.node }
}
```

Minimal code to cause a memory exception in safe Rust:

```rust
#[cfg(test)]
mod test {
    use iprange::IpRange;
    use ipnet::Ipv4Net;
    fn create_iter() -> Box<dyn Iterator<Item=Ipv4Net>> {
        let mut ip_range: IpRange<Ipv4Net> = IpRange::new();
        ip_range.add("10.0.0.0/8".parse().unwrap());
        Box::new(ip_range.into_iter().map(|x| x.subnets(32)).flatten().flatten())
    }
    #[test]
    fn test_find_free() {
        let mut ip_range_iter = create_iter();
        assert_eq!(Some("10.0.0.0/32".parse().unwrap()), ip_range_iter.next());
    }
}
```

**Comment by sticnarf** [comment]
Thanks for the issue. It is indeed a terrible problem.

#12 adds a lifetime to the iterator, then invalid usage of the iterator can be detected by the compiler.

I will release 0.6.4 with the fix. Although it is a breaking change, it is intended not to bump 0.7 so users can be aware of this soundness bug.
