### ISSUE TITLE
Mixed v4/v6 ranges?

### ISSUE THREAD

**Issue by jbr** [sticnarf/iprange-rs#13]
Hi and thanks for this crate! I'm looking at using it to store user generated ip ranges which might be v4 or v6 and then test whether an ip which might be v4 or v6 matches the appropriate range. Is this something that would make sense to PR to this crate, or is it out of scope?

**Comment by jbr** [comment]
context: this is for behavior like [this](https://expressjs.com/en/guide/behind-proxies.html#:~:text=An%20IP%20address%2C%20subnet%2C%20or%20an%20array%20of%20IP%20addresses%20and%20subnets%20to%20trust%20as%20being%20a%20reverse%20proxy.%20The%20following%20list%20shows%20the%20pre-configured%20subnet%20names) where the ip to be tested is provided by a http header and the range is provided by an application author

**Comment by sticnarf** [comment]
This feature, IMHO, is not really necessary to be provided by this crate. It is easy to create `IpRange`s for IPv4 and IPv6 separately and test the input according to its type.

**Comment by jbr** [comment]
Ok, thanks!

**Comment by jbr** [comment]
If anyone finds this issue later looking for the same behavior: [cidr::AnyIpCidr](https://docs.rs/cidr/0.1.1/cidr/enum.AnyIpCidr.html)
