### ISSUE TITLE
std::rc::Rc<std::cell::RefCell<iprange::IpTrieNode>>` cannot be sent between threads safely

### ISSUE THREAD

**Issue by miquels** [sticnarf/iprange-rs#8]
I wanted to use this crate in an actix-web application to restrict access to clients within certain IP ranges. The configuration is placed in an Arc so that multiple HttpServers can use it. But alas, an IpRange is not Send. I do not think this is an uncommon usecase...

Suggestion: have a way for an IpRange to produce a IpRangeRo, a read-only final version of the trie, that can safely be sent/shared between threads.

Thanks.

**Comment by miquels** [comment]
Note that in the mean time I've implemented something myself (a sorted Vec<> of IpNets on which I do a binary search) that will do for now, so I do not really need this functionality (it would just be a small optimization I think). So feel free to close the issue if you are not going to implement it.

**Comment by sticnarf** [comment]
I remove all the Rc<RefCell> and use references instead. 

Now `IpRange` is `Sync` and `Send`.

Check the new version if you are still interested.
