### ISSUE TITLE
Expose API for checking if IpRange is empty

### ISSUE THREAD

**Issue by zonyitoo** [sticnarf/iprange-rs#9]
Currently the only way to check if `IpRange` is empty is by `iter()`

```rust
let is_empty = ip_range.iter().next().is_none();
```

But `iter()` aka `into_iter()` requires allocation of a `VecDeque`, which is quite unnecessary for use case that only wants to check if this `IpRange` is empty or not.

A easy solution:

```rust
fn is_empty(&self) {
    self.trie.root.is_none()
}
```

I could submit a PR for this.

**Comment by sticnarf** [comment]
Added. e23971491d78165dd9279422d69c8f766fa7be48
